version: "3"
#https://github.com/docker/awesome-compose/tree/master/react-express-mysql
#above link should be used as reference. 
#DockerFile and compose should be in the root of your project
#only use --build with compose up if you plan to rebuild your image before starting container
services:
  web:
    build:
      context: ./spotify-mash #context tells docker where to look for dockerFile. If it /frontend then write frontend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    environment:
      SPOTIFY_CLIENT_ID: YOUR_CLIENT_ID
      SPOTIFY_CLIENT_SECRET: YOUR_CLIENT_SECRET
      NODE_ENV: development
      DATABASE_URL: postgresql://root:root@db:5432/postgres?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: YOUR_NEXTAUTH_SECRET
      REDIS_URL: redis://@redis:6379
    volumes:
      - ./spotify-mash/src:/app/src
      - ./spotify-mash/package.json:/app/package.json
      - /app/node_modules
      - /app/.next
      - ./spotify-mash/next.config.js:/app/next.config.js
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - 6379:6379

volumes:
  postgres-data:
