version: "3"
#https://github.com/docker/awesome-compose/tree/master/react-express-mysql
#above link should be used as reference. 
#DockerFile and compose should be in the root of your project
#only use --build with compose up if you plan to rebuild your image before starting container
services:
  web:
    build:
      context: ./spotify-mash #context tells docker where to look for dockerFile. If it /frontend then write frontend
      dockerfile: Dockerfile
    container_name: web
    environment:
      SPOTIFY_CLIENT_ID: 0c4be8bf30024d59bf0794481a8011d5
      SPOTIFY_CLIENT_SECRET: 469f33636c2241288a0a6e1a981030cd
      NODE_ENV: development
      REDIS_URL: redis://@redis:6379
      DATABASE_URL: postgresql://root:root@db:5432/postgres?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: sSxmLn5g68x9V3fyzSScXKBQ9ltIFw12Vlv8qJvCkX0=
    volumes:
      - ./spotify-mash/src:/app/src
      - ./spotify-mash/package.json:/app/package.json
      - /app/node_modules
      - /app/.next
      - ./spotify-mash/next.config.js:/app/next.config.js
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - 6379:6379
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: DockerFile
    command: node server.js
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports: 
      - 3001:3000
    environment:
      REDIS_URL: redis://@redis:6379
  function:
    container_name: cloud-function
    image: python:3.12.0-bullseye
    ports:
     - 8080:8080
    volumes:
      - ./cloud-function:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      REDIS_HOST_NAME: redis
      REDIS_PORT_NUMBER: 6379

volumes:
  postgres-data:
