version: "3"
#https://github.com/docker/awesome-compose/tree/master/react-express-mysql
#above link should be used as reference. 
#DockerFile and compose should be in the root of your project
#only use --build with compose up if you plan to rebuild your image before starting container
services:
  web:
    # image: australia-southeast1-docker.pkg.dev/spotify-mash-project-live/project-spotify-mash/web:0.2
    build:
      context: ./spotify-mash #context tells docker where to look for dockerFile. If it /frontend then write frontend
      dockerfile: Dockerfile
    container_name: web
    command: sleep infinite
    environment:
      GCP_PROJECT: YOUR_GCP_PROJECT_ID
      GCP_LOCATION: YOUR_GCP_LOCATION 
      GCP_QUEUE: YOUR_GCP_QUEUE_ID 
      GCP_SERVICE_ACCOUNT_EMAIL: YOUR_GCP_SERVICE_ACCOUNT
      GCP_TARGET_RESOURCE: YOUR_GCP_TARGET_RESOURCE
      NEXTAUTH_SECRET: YOUR_NEXTAUTH_SECRET
      NEXTAUTH_URL: YOUR_NEXTAUTH_URL
      SPOTIFY_CLIENT_ID: YOUR_SPOTIFY_CLIENT_ID
      SPOTIFY_CLIENT_SECRET: YOUR_SPOTIFY_CLIENT_SECRET
      GOOGLE_APPLICATION_CREDENTIALS: /app/adc.json
    volumes:
      - ./spotify-mash/public:/app/public
      - ./spotify-mash/src:/app/src
      - ./spotify-mash/package.json:/app/package.json
      - /app/node_modules
      - ./spotify-mash/next.config.js:/app/next.config.js
      # - ./spotify-mash/adc.json:/app/adc.json
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    container_name: redis_server
    build: 
      dockerfile: DockerFile.redis
    ports:
      - 6379:6379
    command: /bin/sh -c "./script.sh & redis-server"
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: DockerFile
    command: sleep infinite
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      REDIS_URL: redis://@redis:6379
  function:
    container_name: cloud-function
    image: python:3.12.0-bullseye
    ports:
      - 8080:8080
    volumes:
      - ./cloud-function:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"