version: "3"
#https://github.com/docker/awesome-compose/tree/master/react-express-mysql
#above link should be used as reference. 
#DockerFile and compose should be in the root of your project
#only use --build with compose up if you plan to rebuild your image before starting container
services:
  web:
    build:
      context: ./spotify-mash #context tells docker where to look for dockerFile. If it /frontend then write frontend
      dockerfile: Dockerfile
    container_name: web
    command: sleep infinite
    environment:
      NODE_ENV: production
      NEXTAUTH_SECRET: 7nVuq++42yjHTSJ6FG9h0I5dMjM3bj3+b/fv92/2Bqc=
      NEXTAUTH_URL: http://localhost:3000
      SPOTIFY_CLIENT_ID: YOUR SPOTIFY CLIENT ID
      SPOTIFY_CLIENT_SECRET: YOUR SPOTIFY CLIENT SECRET
    volumes:
      - ./spotify-mash/public:/app/public
      - ./spotify-mash/src:/app/src
      - ./spotify-mash/package.json:/app/package.json
      - /app/node_modules
      - ./spotify-mash/next.config.js:/app/next.config.js
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - 6379:6379
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: DockerFile
    command: sleep infinite
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      REDIS_URL: redis://@redis:6379
  function:
    container_name: cloud-function
    image: python:3.12.0-bullseye
    ports:
      - 8080:8080
    volumes:
      - ./cloud-function:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
