FROM node:18-alpine AS build

WORKDIR /app

COPY . .

RUN npm install && npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=build /app/dist /app/dist

COPY --from=build /app/package.json .

RUN npm install --production

EXPOSE 8080

CMD npm run start
