FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json tsconfig*.json /app/

RUN npm install 

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY package*.json /app

COPY --from=build /app/dist /app/dist

RUN npm install --production

EXPOSE 8080

CMD node dist/server.js
