FROM node:alpine AS build 

ARG SOCKET_RESOURCE_URL

WORKDIR /app

COPY package*.json tsconfig*.json ./

COPY . .

RUN npm install && NEXT_PUBLIC_SOCKET_RESOURCE=${SOCKET_RESOURCE_URL} npm run build

FROM node:18-alpine AS runner

WORKDIR /app

COPY package*.json .

COPY --from=build /app/next.config.js /app/next.config.js

COPY --from=build /app/.next /app/.next 

RUN npm install --production

EXPOSE 3000

CMD npm run start